### ISSUE TITLE
Github and pip Release out of sync

### ISSUE THREAD

**Issue by DanielHabenicht** [obsrvbl/gcp-flowlogs-reader#20]
Hi, thanks for sharing the tool! 

While using it I've come across this error: 

![image](https://user-images.githubusercontent.com/13590797/124496125-50d8b600-ddb9-11eb-999c-5b8d966407ee.png)

Looking into the code this was already fixed. But installing the package with `pip install gcp-flowlogs-reader`installed version `1.0.0` which is not published on GitHub but seems to be an older version than [v0.7.1](https://github.com/obsrvbl/gcp-flowlogs-reader/releases/tag/v0.7.1). 

Installing it with `pip install gcp_flowlogs_reader==0.7.1` fixed the issue. 

Would be great if you can fix the release.

**Comment by bbayles** [comment]
Currently 0.7.1 is the better release to use, because 1.0.0 requires the GCP Logging library v2. However, those v2 libraries from Google [are broken](https://github.com/googleapis/python-logging/issues/136#issuecomment-777776681) in an important way (please note I am speaking on my behalf as an independent developer and not on behalf of my employer, state, country, or planet).

When the v2 (or later) libraries allow for proper paging, then I'll release another 1.x version.

Thanks!

**Comment by DanielHabenicht** [comment]
Ahh, good to know. Then it's not your fault at all. Thanks for clearing up :)
